<?php

namespace Database\Seeders;

use App\Models\SaProfile;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $users = [
            [
                'id_number' => 114,
                'first_name' => 'Jose',
                'last_name' => 'Mercado',
                'middle_initial' => 'M',
                'gender' => 'Male',
                'contact_number' => 639198887654,
                'birth_date' => '1997-04-28',
                'birth_place' => 'Davao City, Philippines',
                'course_program' => 'BS Electronics Engineering',
                'status' => 'active',
            ],
            [
                'id_number' => 115,
                'first_name' => 'Alexander',
                'last_name' => 'Reyes',
                'middle_initial' => 'T',
                'gender' => 'Male',
                'contact_number' => 639168761234,
                'birth_date' => '2000-08-18',
                'birth_place' => 'Mandaluyong, Philippines',
                'course_program' => 'BS Computer Science',
                'status' => 'active',
            ],
            [
                'id_number' => 116,
                'first_name' => 'Emily',
                'last_name' => 'Villanueva',
                'middle_initial' => 'B',
                'gender' => 'Female',
                'contact_number' => 639271234567,
                'birth_date' => '1999-02-21',
                'birth_place' => 'Pasig City, Philippines',
                'course_program' => 'BS Information Technology',
                'status' => 'active',
            ],
            [
                'id_number' => 117,
                'first_name' => 'John',
                'last_name' => 'Smith',
                'middle_initial' => 'A',
                'gender' => 'Male',
                'contact_number' => 639165987654,
                'birth_date' => '1998-05-15',
                'birth_place' => 'Manila, Philippines',
                'course_program' => 'BS Information Technology',
                'status' => 'active',
            ],
            [
                'id_number' => 118,
                'first_name' => 'Maria',
                'last_name' => 'Jones',
                'middle_initial' => 'P',
                'gender' => 'Female',
                'contact_number' => 639175648231,
                'birth_date' => '1999-03-22',
                'birth_place' => 'Cebu City, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],
            [
                'id_number' => 119,
                'first_name' => 'Peter',
                'last_name' => 'Parker',
                'middle_initial' => 'B',
                'gender' => 'Male',
                'contact_number' => 639165765432,
                'birth_date' => '1999-05-02',
                'birth_place' => 'Quezon City, Philippines',
                'course_program' => 'BS Information Technology',
                'status' => 'active',
            ],
            [
                'id_number' => 120,
                'first_name' => 'Bruce',
                'last_name' => 'Lane',
                'middle_initial' => 'W',
                'gender' => 'Male',
                'contact_number' => 639271232345,
                'birth_date' => '1997-07-07',
                'birth_place' => 'Batangas, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],
            [
                'id_number' => 121,
                'first_name' => 'Clark',
                'last_name' => 'Kent',
                'middle_initial' => 'S',
                'gender' => 'Male',
                'contact_number' => 639165987321,
                'birth_date' => '1997-10-10',
                'birth_place' => 'Quezon City, Philippines',
                'course_program' => 'BS Computer Science',
                'status' => 'active',
            ],
            [
                'id_number' => 122,
                'first_name' => 'Diana',
                'last_name' => 'Prince',
                'middle_initial' => 'L',
                'gender' => 'Female',
                'contact_number' => 639174561234,
                'birth_date' => '1998-08-12',
                'birth_place' => 'Makati, Philippines',
                'course_program' => 'BS Information Technology',
                'status' => 'active',
            ],
            [
                'id_number' => 123,
                'first_name' => 'Barry',
                'last_name' => 'Allen',
                'middle_initial' => 'A',
                'gender' => 'Male',
                'contact_number' => 639196784321,
                'birth_date' => '1999-09-23',
                'birth_place' => 'Taguig, Philippines',
                'course_program' => 'BS Electronics Engineering',
                'status' => 'active',
            ],
            [
                'id_number' => 124,
                'first_name' => 'Arthur',
                'last_name' => 'Curry',
                'middle_initial' => 'J',
                'gender' => 'Male',
                'contact_number' => 639193214567,
                'birth_date' => '1997-12-15',
                'birth_place' => 'Cebu City, Philippines',
                'course_program' => 'BS Electronics Engineering',
                'status' => 'active',
            ],
            [
                'id_number' => 125,
                'first_name' => 'Victor',
                'last_name' => 'Stone',
                'middle_initial' => 'T',
                'gender' => 'Male',
                'contact_number' => 639165612345,
                'birth_date' => '1998-06-19',
                'birth_place' => 'Davao City, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],
            [
                'id_number' => 126,
                'first_name' => 'Hal',
                'last_name' => 'Jordan',
                'middle_initial' => 'K',
                'gender' => 'Male',
                'contact_number' => 639162345678,
                'birth_date' => '1997-11-05',
                'birth_place' => 'Makati, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],
            [
                'id_number' => 127,
                'first_name' => 'Kyle',
                'last_name' => 'Walker',
                'middle_initial' => 'R',
                'gender' => 'Male',
                'contact_number' => 639194321654,
                'birth_date' => '1998-03-09',
                'birth_place' => 'Pasig City, Philippines',
                'course_program' => 'BS Information Technology',
                'status' => 'active',
            ],
            [
                'id_number' => 128,
                'first_name' => 'Selina',
                'last_name' => 'Kyle',
                'middle_initial' => 'Q',
                'gender' => 'Female',
                'contact_number' => 639197654321,
                'birth_date' => '1999-04-13',
                'birth_place' => 'Manila, Philippines',
                'course_program' => 'BS Computer Science',
                'status' => 'active',
            ],
            [
                'id_number' => 129,
                'first_name' => 'Lois',
                'last_name' => 'Lane',
                'middle_initial' => 'V',
                'gender' => 'Female',
                'contact_number' => 639165765432,
                'birth_date' => '1997-01-22',
                'birth_place' => 'Cebu City, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],
            [
                'id_number' => 130,
                'first_name' => 'Harley',
                'last_name' => 'Quinn',
                'middle_initial' => 'E',
                'gender' => 'Female',
                'contact_number' => 639171234567,
                'birth_date' => '1999-10-25',
                'birth_place' => 'Mandaluyong, Philippines',
                'course_program' => 'BS Computer Science',
                'status' => 'active',
            ],
            [
                'id_number' => 131,
                'first_name' => 'Dick',
                'last_name' => 'Grayson',
                'middle_initial' => 'H',
                'gender' => 'Male',
                'contact_number' => 639165612678,
                'birth_date' => '1997-06-07',
                'birth_place' => 'Taguig, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],
            [
                'id_number' => 132,
                'first_name' => 'Jason',
                'last_name' => 'Wood',
                'middle_initial' => 'R',
                'gender' => 'Male',
                'contact_number' => 639197543210,
                'birth_date' => '1998-12-20',
                'birth_place' => 'Manila, Philippines',
                'course_program' => 'BS Electronics Engineering',
                'status' => 'active',
            ],[
                'id_number' => 133,
                'first_name' => 'Tim',
                'last_name' => 'Drake',
                'middle_initial' => 'R',
                'gender' => 'Male',
                'contact_number' => 639468132576,
                'birth_date' => '1995-12-21',
                'birth_place' => 'Manila, Philippines',
                'course_program' => 'BS Business Administration',
                'status' => 'active',
            ],[
                'id_number' => 134,
                'first_name' => 'Steve',
                'last_name' => 'Rogers',
                'middle_initial' => 'S',
                'gender' => 'Male',
                'contact_number' => 639648216799,
                'birth_date' => '1995-01-31',
                'birth_place' => 'Quezon, Philippines',
                'course_program' => 'BS Information Technology',
                'status' => 'active',
            ]
        ];

        foreach ($users as $userData) {
            $user = User::where('id_number', $userData['id_number'])->first();
            if ($user) {
                SaProfile::create([
                    'user_id' => $user->id_number,
                    'first_name' => $userData['first_name'],
                    'last_name' => $userData['last_name'],
                    'middle_initial' => $userData['middle_initial'],
                    'gender' => $userData['gender'],
                    'contact_number' => $userData['contact_number'],
                    'birth_date' => $userData['birth_date'],
                    'birth_place' => $userData['birth_place'],
                    'course_program' => $userData['course_program'],
                    'status' => $userData['status'],
                ]);
            }
        }

    }
}
